
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class login extends javax.swing.JFrame {
    private Object rs;
    private Object[] JFCase;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        checkuser = new javax.swing.JCheckBox();
        checkadmin = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login page");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(240, 240, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText(" CRIDENTIALS ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 53, -1, 40));

        jLabel3.setBackground(new java.awt.Color(51, 255, 51));
        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("USERNAME OR EMAIL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 122, 210, 31));

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 118, 33));

        username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 121, 260, 31));

        password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 171, 260, 33));

        btnlogin.setBackground(new java.awt.Color(255, 247, 240));
        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 153, 153));
        btnlogin.setText("LOGIN ");
        btnlogin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        btnlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnloginKeyPressed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 243, 80, 37));

        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(51, 0, 247));
        btnRegister.setText("Dont have account  (Register user)");
        btnRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 321, 234, 35));

        exit.setBackground(new java.awt.Color(255, 247, 240));
        exit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 51, 255));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 320, 96, 35));

        checkuser.setBackground(new java.awt.Color(255, 153, 204));
        checkuser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        checkuser.setText("User");
        checkuser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        checkuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkuserActionPerformed(evt);
            }
        });
        jPanel1.add(checkuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 14, 63, 31));

        checkadmin.setBackground(new java.awt.Color(255, 153, 255));
        checkadmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        checkadmin.setText("Admin");
        checkadmin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        checkadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkadminActionPerformed(evt);
            }
        });
        jPanel1.add(checkadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 14, -1, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 530, 380));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 204));
        jLabel10.setText("SMART CITY GUIDE ");
        jPanel3.add(jLabel10);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setAutoscrolls(true);
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel5KeyTyped(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        setSize(new java.awt.Dimension(1425, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

  //Codes that help to link or direct to registration page 
        
Register reg = new Register();
reg.setVisible(true);
this.hide();

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
      
      String id=username.getText();
      String pass=password.getText();
     
if(checkuser.isSelected()){
    try{
        Class.forName("com.mysql.jdbc.Driver");
         //connection statement and resultset is for connecting to database and execute query stated 
       
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/register","root","");
    Statement stmt=conn.createStatement();

    ResultSet ss = stmt.executeQuery("select * from registration where username='"+id+"'and password='"+pass+"' or email='"+id+"'and password='"+pass+"'");
    
    // Codes to check whether textfields is empty so that the alter message is displayed
      if("".equals(id)){JOptionPane.showMessageDialog(this,"Enter username");}
      else if("".equals(pass)){JOptionPane.showMessageDialog(this,"Enter password");}
      
      // Codes that link to next page if all condition are true 
      else if(ss.next())
    {
       HOMEPAGE hom=new HOMEPAGE();
       hom.setVisible(true);
       this.hide();
    
        // codes that will output Alter message for incorect cridentials either wrong username or password
    }else
       { JOptionPane.showMessageDialog(this,"incorrect cridentials");} 
      
     } 
    
    catch (SQLException e) 
          { System.out.println(e); } 
    
    catch (ClassNotFoundException ex) 
    { Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex); }
    
    }
     
else if(checkadmin.isSelected()){
    try{
       Class.forName("com.mysql.jdbc.Driver");
        //connection statement and resultset is for connecting to database and execute query stated 
       
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/register","root","");
    Statement stmt=conn.createStatement();

    ResultSet ss = stmt.executeQuery("select * from admin where USERNAME='"+id+"'and PASSWORD='"+pass+"'or EMAIL='"+id+"'and PASSWORD='"+pass+"'");
      
    // Codes to check whether textfields is empty so that the alter message is displayed 
    
      if("".equals(id)){JOptionPane.showMessageDialog(this,"Enter username");}
      else if("".equals(pass)){JOptionPane.showMessageDialog(this,"Enter password");}
      
    // Codes that link to next page if all condition are true 
      
      else if(ss.next())
          
    {
       adminpage hom=new adminpage();
       hom.setVisible(true);
        this.hide();
    }
      // codes that will output Alter message for incorect cridentials either wrong username or password
      
      else { JOptionPane.showMessageDialog(this,"incorrect cridentials"); }
        
    }  
   
    catch (SQLException e)
    { System.out.println(e); } 
    
    catch (ClassNotFoundException ex) 
    { Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex); }
   
    }
else
     {JOptionPane.showMessageDialog(this,"Check  USER MODE or ADMIN MODE "); }
     
    }//GEN-LAST:event_btnloginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void checkuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkuserActionPerformed
    // CODE TO DISABLE ADMIN WHEN USER IS SELECTED
        
        if(checkuser.isSelected())
        { checkadmin.setSelected(false);}
        
    }//GEN-LAST:event_checkuserActionPerformed

    private void checkadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkadminActionPerformed
        // CODE TO DISABLE USER WHEN ADMIN IS SELECTED
        
        if(checkadmin.isSelected())
        { checkuser.setSelected(false);}
        
    }//GEN-LAST:event_checkadminActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased

    }//GEN-LAST:event_passwordKeyReleased

    private void btnloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnloginKeyPressed
  
    }//GEN-LAST:event_btnloginKeyPressed
    
    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
    
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jLabel5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox checkadmin;
    private javax.swing.JCheckBox checkuser;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); 
//To change body of generated methods, choose Tools | Templates.
    }

    private static class Resultset {

        public Resultset() {
        }
    }
}
